export const resourceConfigs = [
  {
    key: "hotels",
    label: "Hotels",
    endpoint: "/api/hotels",
    columns: ["code", "name", "brand", "city", "country", "status"],
    fields: [
      { name: "code", label: "Code" },
      { name: "name", label: "Name" },
      { name: "brand", label: "Brand" },
      { name: "country", label: "Country" },
      { name: "city", label: "City" },
      { name: "district", label: "District" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "star_rating", label: "Star Rating", type: "number" },
      { name: "timezone", label: "Timezone" },
      { name: "checkin_time", label: "Check-in Time", type: "time" },
      { name: "checkout_time", label: "Check-out Time", type: "time" },
      { name: "total_rooms", label: "Total Rooms", type: "number" },
      { name: "status", label: "Status" },
    ],
  },
  {
    key: "room-types",
    label: "Room Types",
    endpoint: "/api/room-types",
    columns: ["hotel_id", "code", "name", "max_adults", "max_children", "base_price"],
    fields: [
      { name: "hotel_id", label: "Hotel ID" },
      { name: "code", label: "Code" },
      { name: "name", label: "Name" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "room_size", label: "Room Size", type: "number" },
      { name: "max_adults", label: "Max Adults", type: "number" },
      { name: "max_children", label: "Max Children", type: "number" },
      { name: "bed_type", label: "Bed Type" },
      { name: "smoking_allowed", label: "Smoking Allowed", type: "checkbox" },
      { name: "base_price", label: "Base Price", type: "number", step: "0.01" },
      { name: "total_inventory", label: "Total Inventory", type: "number" },
    ],
  },
  {
    key: "rooms",
    label: "Rooms",
    endpoint: "/api/rooms",
    columns: ["hotel_id", "room_type_id", "room_number", "floor_number", "room_status"],
    fields: [
      { name: "hotel_id", label: "Hotel ID" },
      { name: "room_type_id", label: "Room Type ID" },
      { name: "room_number", label: "Room Number" },
      { name: "floor_number", label: "Floor Number", type: "number" },
      { name: "room_status", label: "Room Status" },
      { name: "housekeeping_status", label: "Housekeeping Status" },
    ],
  },
  {
    key: "amenities",
    label: "Amenities",
    endpoint: "/api/amenities",
    columns: ["code", "name", "icon", "description"],
    fields: [
      { name: "code", label: "Code" },
      { name: "name", label: "Name" },
      { name: "icon", label: "Icon" },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    key: "facilities",
    label: "Facilities",
    endpoint: "/api/facilities",
    columns: ["hotel_id", "code", "name", "facility_type", "base_price", "is_active"],
    fields: [
      { name: "hotel_id", label: "Hotel ID" },
      { name: "code", label: "Code" },
      { name: "name", label: "Name" },
      { name: "description", label: "Description", type: "textarea" },
      { name: "facility_type", label: "Facility Type" },
      { name: "price_type", label: "Price Type" },
      { name: "base_price", label: "Base Price", type: "number", step: "0.01" },
      { name: "is_active", label: "Active", type: "checkbox" },
    ],
  },
  {
    key: "rate-plans",
    label: "Rate Plans",
    endpoint: "/api/rate-plans",
    columns: ["hotel_id", "code", "name", "meal_plan", "refundable", "active"],
    fields: [
      { name: "hotel_id", label: "Hotel ID" },
      { name: "code", label: "Code" },
      { name: "name", label: "Name" },
      { name: "refundable", label: "Refundable", type: "checkbox" },
      { name: "cancellation_policy", label: "Cancellation Policy", type: "textarea" },
      { name: "meal_plan", label: "Meal Plan" },
      { name: "active", label: "Active", type: "checkbox" },
    ],
  },
  {
    key: "daily-inventory",
    label: "Daily Inventory",
    endpoint: "/api/daily-inventory",
    columns: ["hotel_id", "room_type_id", "inventory_date", "available_inventory", "stop_sell", "closed"],
    fields: [
      { name: "hotel_id", label: "Hotel ID" },
      { name: "room_type_id", label: "Room Type ID" },
      { name: "inventory_date", label: "Inventory Date", type: "date" },
      { name: "total_inventory", label: "Total Inventory", type: "number" },
      { name: "sold_inventory", label: "Sold Inventory", type: "number" },
      { name: "available_inventory", label: "Available Inventory", type: "number" },
      { name: "stop_sell", label: "Stop Sell", type: "checkbox" },
      { name: "closed", label: "Closed", type: "checkbox" },
    ],
  },
  {
    key: "daily-rates",
    label: "Daily Rates",
    endpoint: "/api/daily-rates",
    columns: ["hotel_id", "room_type_id", "rate_plan_id", "rate_date", "final_rate", "currency"],
    fields: [
      { name: "hotel_id", label: "Hotel ID" },
      { name: "room_type_id", label: "Room Type ID" },
      { name: "rate_plan_id", label: "Rate Plan ID" },
      { name: "rate_date", label: "Rate Date", type: "date" },
      { name: "base_rate", label: "Base Rate", type: "number", step: "0.01" },
      { name: "occupancy_factor", label: "Occupancy Factor", type: "number", step: "0.01" },
      { name: "season_factor", label: "Season Factor", type: "number", step: "0.01" },
      { name: "weekend_factor", label: "Weekend Factor", type: "number", step: "0.01" },
      { name: "event_factor", label: "Event Factor", type: "number", step: "0.01" },
      { name: "demand_factor", label: "Demand Factor", type: "number", step: "0.01" },
      { name: "final_rate", label: "Final Rate", type: "number", step: "0.01" },
      { name: "currency", label: "Currency" },
      { name: "stop_sell", label: "Stop Sell", type: "checkbox" },
      { name: "closed", label: "Closed", type: "checkbox" },
    ],
  },
  {
    key: "promotions",
    label: "Promotions",
    endpoint: "/api/promotions",
    columns: ["code", "name", "discount_type", "discount_value", "valid_from", "valid_to"],
    fields: [
      { name: "code", label: "Code" },
      { name: "name", label: "Name" },
      { name: "discount_type", label: "Discount Type" },
      { name: "discount_value", label: "Discount Value", type: "number", step: "0.01" },
      { name: "valid_from", label: "Valid From", type: "date" },
      { name: "valid_to", label: "Valid To", type: "date" },
      { name: "usage_limit", label: "Usage Limit", type: "number" },
      { name: "active", label: "Active", type: "checkbox" },
    ],
  },
  {
    key: "payments",
    label: "Payments",
    endpoint: "/api/payments",
    columns: ["booking_id", "payment_method", "provider", "amount", "payment_status"],
    fields: [
      { name: "booking_id", label: "Booking ID" },
      { name: "payment_method", label: "Payment Method" },
      { name: "provider", label: "Provider" },
      { name: "transaction_id", label: "Transaction ID" },
      { name: "amount", label: "Amount", type: "number", step: "0.01" },
      { name: "payment_status", label: "Payment Status" },
      { name: "paid_at", label: "Paid At", type: "datetime-local" },
    ],
  },
];

export const workspaceHighlights = [
  {
    title: "Auth",
    description: "Client register/login, admin login, token-based profile check.",
    endpoints: ["/api/auth/register", "/api/auth/login", "/api/auth/me"],
  },
  {
    title: "Catalog CRUD",
    description: "Hotel inventory, rooms, amenities, facilities, rate plans, daily inventory and rates.",
    endpoints: ["/api/hotels", "/api/room-types", "/api/rooms", "/api/daily-rates"],
  },
  {
    title: "Guest Journey",
    description: "Search room availability, quote runtime price, then create booking.",
    endpoints: ["/api/search", "/api/pricing/quote", "/api/bookings"],
  },
];
